name: pull request

on:
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: node.js 12
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: installing
        run: npm ci
      - name: testing
        run: npm test
