name: Pull Request


on:
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ master ]

jobs:

  release:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: node.js 12
        uses: actions/setup-node@v2
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
          cache: 'npm'

      - name: installing
        run: npm ci

      - name: linters
        uses: wearerequired/lint-action@v1
        with:
          prettier: true
          prettier_extensions: ts,tsx,js,jsx,json,md,mdx,css
          continue_on_error: false

      - name: testing
        run: npm test -- --coverage

      - name: building
        run: npm run build

      - name: building documents
        run: npm run build-storybook
