name: release

on:
  push:
    branches:
      - master

jobs:
  setup:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: node.js 12
        uses: actions/setup-node@v2
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
          cache: 'npm'

      - name: installing
        run: npm ci

  test:
    needs: setup
    runs-on: ubuntu-20.04

    steps:
      - name: testing
        run: npm test -- --coverage


  build:
    needs: test
    runs-on: ubuntu-20.04

    steps:

      - name: building
        run: npm run build

      - name: building documents
        run: npm run build-storybook

      - name: coveralls
        uses: coverallsapp/github-action@v1.1.2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

  release:
    needs: test
    runs-on: ubuntu-20.04

    steps:
      - name: releasing
        run: npm run semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}

      # publish to gh pages
      - name: publishing documents
        uses: peaceiris/actions-gh-pages@v2
        env:
          PERSONAL_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: ./public
